ctrl:
  endpoint: "ziti-controller-managed-ctrl.example.com:443"
edge:
  advertisedHost: "router1.ziti.example.com"
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.allow-http: "false"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
