global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node_exporters"
    static_configs:
      - targets: ["server1:9100"]

  - job_name: "cadvisors"
    static_configs:
      - targets: ["server1:8080"]
