volumes:
  artifacts:

services:
  preprocessing-service:
    image: hongtringuyen/preprocessing_ziti:latest
    container_name: preprocessing-service
    ports:
      - 5010:5010
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    extra_hosts:
      - "${ZITI_CTRL_ADVERTISED_ADDRESS}:${CLOUD_IP}"
      - "${ZITI_EDGE_ROUTER_ADVERTISED_ADDRESS}:${EDGE_IP}"
      - "${ZITI_CLOUD_ROUTER_ADVERTISED_ADDRESS}:${CLOUD_IP}"
    networks:
      - default
    volumes:
      - /tmp/preprocessing.json:/opt/secret.json
    environment:
      OPENZITI: "true"
      #DOCKER: "true"
      MANUAL_TRACING: true
      OTEL_ENDPOINT: "http://{$JAEGER_IP}:4318/v1/traces"
      cpus: 0.5

  ensemble-service:
    image: hongtringuyen/ensemble_ziti:latest
    container_name: ensemble-service
    ports:
      - 5011:5011
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    extra_hosts:
      - "${ZITI_CTRL_ADVERTISED_ADDRESS}:${CLOUD_IP}"
      - "${ZITI_EDGE_ROUTER_ADVERTISED_ADDRESS}:${EDGE_IP}"
      - "${ZITI_CLOUD_ROUTER_ADVERTISED_ADDRESS}:${CLOUD_IP}"
    networks:
      - default
    volumes:
      - /tmp/ensemble.json:/opt/secret.json
    #entrypoint: ["/bin/bash", "-c", "/usr/local/bin/install-ziti-edge-tunnel.sh"]
    environment:
      OPENZITI: "true"
      #DOCKER: "true"
      SEND_TO_QUEUE: true
      MANUAL_TRACING: true
      OTEL_ENDPOINT: "http://{$JAEGER_IP}:4318/v1/traces"
      cpus: 0.5

  mobilenetv2-service:
    image: hongtringuyen/inference_ziti:latest
    container_name: mobilenetv2-service
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    extra_hosts:
      - "${ZITI_CTRL_ADVERTISED_ADDRESS}:${CLOUD_IP}"
      - "${ZITI_EDGE_ROUTER_ADVERTISED_ADDRESS}:${EDGE_IP}"
      - "${ZITI_CLOUD_ROUTER_ADVERTISED_ADDRESS}:${CLOUD_IP}"
    networks:
      - default
    volumes:
      - /tmp/mobilenetv2.json:/opt/secret.json
    #entrypoint: ["/bin/bash", "-c", "/usr/local/bin/install-ziti-edge-tunnel.sh"]
    environment:
      OPENZITI: "true"
      #DOCKER: "true"
      MANUAL_TRACING: true
      OTEL_ENDPOINT: "http://{$JAEGER_IP}:4318/v1/traces"
      cpus: 0.5

  efficientnetb0-service:
    image: hongtringuyen/inference_ziti:latest
    container_name: efficientnetb0-service
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    extra_hosts:
      - "${ZITI_CTRL_ADVERTISED_ADDRESS}:${CLOUD_IP}"
      - "${ZITI_EDGE_ROUTER_ADVERTISED_ADDRESS}:${EDGE_IP}"
      - "${ZITI_CLOUD_ROUTER_ADVERTISED_ADDRESS}:${CLOUD_IP}"
    networks:
      - default
    volumes:
      - /tmp/efficientnetb0.json:/opt/secret.json
    #entrypoint: ["/bin/bash", "-c", "/usr/local/bin/install-ziti-edge-tunnel.sh"]
    environment:
      OPENZITI: "true"
      #DOCKER: "true"
      MANUAL_TRACING: true
      OTEL_ENDPOINT: "http://{$JAEGER_IP}:4318/v1/traces"
      cpus: 0.5
