#  run script to connect serverss to the openziti
#
# networks:
#   default:
#   shared_ziti_network:
#     external: true
volumes:
  artifacts:

services:
  preprocessing-service:
    image: rdsea/preprocessing:latest
    container_name: preprocessing-service
    ports:
      - 5010:5010
      - 5201:5201 #for iperf testing
    #working_dir: /web-server
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    extra_hosts:
    - "ziti-edge-controller:192.168.1.2"
    - "ziti-edge-router:192.168.1.3"
    networks:
      - default
    volumes:
      - ./install-ziti-edge-tunnel.sh:/data_ziti/install-ziti-edge-tunnel.sh
      - ./artifacts:/data_ziti/
    #entrypoint: ["/bin/bash", "-c", "/usr/local/bin/install-ziti-edge-tunnel.sh"]

  ensemble:
    image: rdsea/ensemble:latest
    container_name: ensemble
    ports:
      - 5011:5011
      - 5202:5202 #for iperf testing
    #working_dir: /proc-server
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    extra_hosts:
    - "ziti-edge-controller:192.168.1.2"
    - "ziti-edge-router:192.168.1.3"
    networks:
      - default
    volumes:
      - ./install-ziti-edge-tunnel.sh:/data_ziti/install-ziti-edge-tunnel.sh
      - ./artifacts:/data_ziti/
    #entrypoint: ["/bin/bash", "-c", "/usr/local/bin/install-ziti-edge-tunnel.sh"]

  mobilenetv2-service:
    image: rdsea/inference:cpu
    container_name: mobilenetv2-service
    ports:
      - 5012:5012
      #- 5000:5000
      - 5203:5203 #for iperf testing
    #working_dir: /inference
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    extra_hosts:
    - "ziti-edge-controller:192.168.1.2"
    - "ziti-edge-router:192.168.1.3"
    networks:
      - default
    volumes:
      - ./install-ziti-edge-tunnel.sh:/data_ziti/install-ziti-edge-tunnel.sh
      - ./artifacts:/data_ziti/
    #entrypoint: ["/bin/bash", "-c", "/usr/local/bin/install-ziti-edge-tunnel.sh"]

  efficientnetb0-service:
    image: rdsea/inference:cpu
    container_name: efficientnetb0-service
    ports:
      - 5013:5012
      #- 5000:5000
      - 5204:5203 #for iperf testing
    #working_dir: /inference
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    extra_hosts:
    - "ziti-edge-controller:192.168.1.2"
    - "ziti-edge-router:192.168.1.3"
    networks:
      - default
    volumes:
      - ./install-ziti-edge-tunnel.sh:/data_ziti/install-ziti-edge-tunnel.sh
      - ./artifacts:/data_ziti/
    #entrypoint: ["/bin/bash", "-c", "/usr/local/bin/install-ziti-edge-tunnel.sh"]

  rabbitmq:
    image: hongtringuyen/messageq-ziti:latest
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitMQ-config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./install-ziti-edge-tunnel.sh:/usr/local/bin/install-ziti-edge-tunnel.sh
      - ./rabbitMQ-config/rabbitmq-env.conf:/etc/rabbitmq/rabbitmq-env.conf
      - ./install-ziti-edge-tunnel.sh:/data_ziti/install-ziti-edge-tunnel.sh
      - ./artifacts:/data_ziti/
    extra_hosts:
    - "ziti-edge-controller:192.168.1.2"
    - "ziti-edge-router:192.168.1.3"
    networks:
      - default
    #entrypoint: ["/bin/bash", "-c", "/usr/local/bin/install-ziti-edge-tunnel.sh"]
