---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessing
  labels:
    app: preprocessing
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: preprocessing
      version: v1
  template:
    metadata:
      labels:
        app: preprocessing
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: preprocessing
          imagePullPolicy: "IfNotPresent"
          image: rdsea/preprocessing
          ports:
            - containerPort: 5010
          env:
            - name: OPENZITI
              value: "true"

        - name: ziti-tunnel
          image: openziti/ziti-tunnel
          args: ["tproxy"]
          env:
            - name: ZITI_IDENTITY_BASENAME
              value: preprocessing # the filename in the volume is sidecar-client.json
          volumeMounts:
            - name: sidecar-client-identity
              mountPath: /netfoundry
              readOnly: true
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 127.0.0.1 # used by the tunneler during startup to verify own DNS for the pod
          - 10.96.0.10 # change to CoreDNS cluster service address
      restartPolicy: Always
      volumes:
        - name: sidecar-client-identity
          secret:
            secretName: preprocessing-sidecar-client-identity
---
apiVersion: v1
kind: Service
metadata:
  name: preprocessing-service
spec:
  ports:
    - port: 5010
      targetPort: 5010
  selector:
    app: preprocessing
