volumes:
  artifacts:

services:
  preprocessing-service:
    image: rdsea/preprocessing_ziti:latest
    container_name: preprocessing-service
    ports:
      - 5010:5010
    #   - 5201:5201 #for iperf testing
    #working_dir: /web-server
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    extra_hosts:
      - "${ZITI_CTRL_ADVERTISED_ADDRESS}:${CLOUD_IP}"
      - "${ZITI_ROUTER_ADVERTISED_ADDRESS}:${EDGE_IP}"
    networks:
      - default
    volumes:
      - /tmp/preprocessing.json:/opt/secret.json

  ensemble:
    image: rdsea/ensemble_ziti:latest
    container_name: ensemble
    ports:
      - 5011:5011
    #   - 5202:5202 #for iperf testing
    #working_dir: /proc-server
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    extra_hosts:
      - "${ZITI_CTRL_ADVERTISED_ADDRESS}:${CLOUD_IP}"
      - "${ZITI_ROUTER_ADVERTISED_ADDRESS}:${EDGE_IP}"
    networks:
      - default
    volumes:
      - /tmp/ensemble.json:/opt/secret.json
    #entrypoint: ["/bin/bash", "-c", "/usr/local/bin/install-ziti-edge-tunnel.sh"]

  mobilenetv2-service:
    image: rdsea/inference_ziti:cpu
    container_name: mobilenetv2-service
    # ports:
    #   - 5012:5012
    #   #- 5000:5000
    #   - 5203:5203 #for iperf testing
    #working_dir: /inference
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    extra_hosts:
      - "${ZITI_CTRL_ADVERTISED_ADDRESS}:${CLOUD_IP}"
      - "${ZITI_ROUTER_ADVERTISED_ADDRESS}:${EDGE_IP}"
    networks:
      - default
    volumes:
      - /tmp/mobilenetv2.json:/opt/secret.json
    #entrypoint: ["/bin/bash", "-c", "/usr/local/bin/install-ziti-edge-tunnel.sh"]

  efficientnetb0-service:
    image: rdsea/inference_ziti:cpu
    container_name: efficientnetb0-service
    # ports:
    #   - 5013:5012
    #   #- 5000:5000
    #   - 5204:5203 #for iperf testing
    #working_dir: /inference
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    extra_hosts:
      - "${ZITI_CTRL_ADVERTISED_ADDRESS}:${CLOUD_IP}"
      - "${ZITI_ROUTER_ADVERTISED_ADDRESS}:${EDGE_IP}"
    networks:
      - default
    volumes:
      - /tmp/efficientnetb0.json:/opt/secret.json
    #entrypoint: ["/bin/bash", "-c", "/usr/local/bin/install-ziti-edge-tunnel.sh"]


